# ============================================================================
# FILE: docker-compose.yaml
# LOCATION: pipelines/01-data_ingestion/02-restructure_ukb_showcase_data/docker-compose.yaml
# PIPELINE POSITION: Main Pipeline 01 → Sub-Pipeline 02
# PURPOSE: Orchestrates UK Biobank data restructuring pipeline with multiple processing services
# ============================================================================

services:
  # Primary Meta-Inventory processor with GPU acceleration (recommended)
  ukb-meta-processor-gpu:
    build: .
    container_name: ukb-meta-processor-gpu
    runtime: nvidia
    volumes:
      - ./scripts:/scripts:ro
      - ../01-ingest_ukb_showcase_data/input:/input:ro
      - ./output-meta:/output
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python /scripts/process_showcase_meta.py

  # CPU-only Meta-Inventory processor (fallback option)
  ukb-meta-processor:
    build: .
    container_name: ukb-meta-processor
    working_dir: /app
    volumes:
      # Scripts mounted from local ./scripts directory
      - ./scripts:/scripts:ro
      # Input data files (needs meta inventory file)
      - ../01-ingest_ukb_showcase_data/input:/input:ro
      # Output directory for generated files
      - ./output-meta:/output
    environment:
      - PYTHONUNBUFFERED=1
    command: python /scripts/process_showcase_meta.py

  # Field category validation - checks for data errors
  field-category-check:
    build: .
    container_name: ukb-field-category-validator
    working_dir: /app
    volumes:
      - ./scripts:/scripts:ro
      - ./output-meta:/output
    environment:
      - PYTHONUNBUFFERED=1
    command: python /scripts/field_category_check.py
    depends_on:
      - ukb-meta-processor

  # Category summary generator
  field-summary:
    build: .
    container_name: ukb-field-summary
    working_dir: /app
    volumes:
      - ./scripts:/scripts:ro
      - ./output-meta:/output
    environment:
      - PYTHONUNBUFFERED=1
    command: python /scripts/field_check.py
    depends_on:
      - ukb-meta-processor

  # AI-powered acronym validation (optional, requires OPENROUTER_API_KEY)
  ai-consortium:
    build: .
    container_name: ai-consortium
    working_dir: /app
    volumes:
      - ./scripts:/scripts:ro
      - ./output-meta:/output
    environment:
      - PYTHONUNBUFFERED=1
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    env_file:
      - .env
    command: python /scripts/ai_consortium_validation.py
    depends_on:
      - ukb-meta-processor